### PR TITLE
Do not redirect while on auth only page

### PR DESCRIPTION
**Pull request by munkeywolf00**
Suggested fix for #44. Please note I have not tested this extensively. 
This is just my idea on how to fix it if it is a bug. Please feel free to close this at anytime.

### CODE REVIEW

**Comment by manchenkoff** [comment]
Hey @munkeywolf00, thanks a lot for the contribution! I'll take a closer look and either merge your suggestion or maybe an improved solution!

**Comment by manchenkoff** [comment]
Hey @munkeywolf00, I was playing around with this suggestion and realized that for my 401 response never occurs, if I have incorrect credentials - Laravel returns a 422 validation error response which doesn't trigger a redirect. 
Can you give more details about why it does return 401 in your app? Do you have a custom validation process unlike the default Laravel one?

**Comment by munkeywolf00** [comment]
Hi @manchenkoff. Here is a sample code. Nothing special.
```
public function authenticate(Request $request): JsonResponse
{
        $credentials = $request->validate([
            'email' => ['required', 'email'],
            'password' => ['required'],
        ]);

        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();

            return response()->json(["status" => auth()->user()], 200);
        }

        return response()->json(["message" => "The provided credentials do not match our records."], 401);
}
```
I believe 422 response code is from validation error, not on a login attempt. Unless validations can check if credentials are correct.

**Comment by manchenkoff** [comment]
@munkeywolf00 I see, thanks. I have checked the latest Laravel app samples, and yeah, they implemented it a bit differently

```php
public function authenticate(): void
{
    $this->ensureIsNotRateLimited();

    if (!Auth::attempt($this->only('email', 'password'), $this->boolean('remember'))) {
        RateLimiter::hit($this->throttleKey());

        throw ValidationException::withMessages([
            'email' => __('auth.failed'),
        ]);
    }

    RateLimiter::clear($this->throttleKey());
}
```

It will throw an exception with a 422 response even if the credentials have the proper type but authentication fails. Anyway, I will check other cases with redirects as well, but you can adjust your backend to be more compatible with the recommended functionality.

**Comment by munkeywolf00** [comment]
@manchenkoff  Thank you. I will adjust my backend so no worries. Can you share where I can read this further? You can close this then.

**Comment by manchenkoff** [comment]
> @manchenkoff Thank you. I will adjust my backend so no worries. Can you share where I can read this further? You can close this then.

This is a [Laravel Breeze repository](https://github.com/laravel/breeze), which is considered an API template and [this is a template of authentication request](https://github.com/laravel/breeze/blob/1.x/stubs/api/app/Http/Requests/Auth/LoginRequest.php).

As for docs, you can check this section - [Laravel Docs](https://laravel.com/docs/10.x/authentication#authenticating-users).

**Comment by munkeywolf00** [comment]
> > @manchenkoff Thank you. I will adjust my backend so no worries. Can you share where I can read this further? You can close this then.
> 
> This is a [Laravel Breeze repository](https://github.com/laravel/breeze), which is considered an API template and [this is a template of authentication request](https://github.com/laravel/breeze/blob/1.x/stubs/api/app/Http/Requests/Auth/LoginRequest.php).
> 
> As for docs, you can check this section - [Laravel Docs](https://laravel.com/docs/10.x/authentication#authenticating-users).

I see. Thanks!

**Comment by manchenkoff** [comment]
Closing this one due to the need for more adjustments. For more details check #44

**Pull request closed without merging**
