### PR TITLE
fix: use relative paths for injected types

### PR DESCRIPTION
**Pull request by ExileofAranei**
Hi, thanks for the package, used it for production at got zero issues and troubles.

This PR solves an issue with injected types using docker container.

The module injects file `types/sanctum.d.ts`, which imports types using absolute paths.

Locally there is no probles resolving such paths:
```typescript
// Generated by nuxt-auth-sanctum module
import type { SanctumAppConfig } from 'E:/development/nuxt-auth-sanctum/src/runtime/types/config.ts';
import type { SanctumGlobalMiddlewarePageMeta } from 'E:/development/nuxt-auth-sanctum/src/runtime/types/meta.ts';
```
But using docker imports looks like that:
```typescript
// Generated by nuxt-auth-sanctum module
import type { SanctumAppConfig } from '/var/www/html/node_modules/nuxt-auth-sanctum/dist/runtime/types/config.ts';
import type { SanctumGlobalMiddlewarePageMeta } from '/var/www/html/node_modules/nuxt-auth-sanctum/dist/runtime/types/meta.ts';
```

I can't reach those paths on local machine, so some type safety is gone, for example using `definePageMeta` there is no type suggestions for `sanctum`.

My attempt to fix that is resolving paths relatively to `<buildDir>/types`. For example:
```typescript
// Generated by nuxt-auth-sanctum module
import type { SanctumAppConfig } from '../../../src/runtime/types/config.ts';
import type { SanctumGlobalMiddlewarePageMeta } from '../../../src/runtime/types/meta.ts';
```

### CODE REVIEW

**Comment by manchenkoff** [comment]
Hey @ExileofAranei, thanks for the contribution! I'll check this out but it looks like it is common practice with the path and probably should be resolved on the Nuxt side first. There are some examples in the modules, such as [sidebase](https://github.com/sidebase/nuxt-auth/blob/main/src/module.ts#L190). 

Do you mind opening an issue for Nuxt as well and linking it here?

**Comment by ExileofAranei** [comment]
Sure, started a [discussion](https://github.com/nuxt/nuxt/discussions/30383) at `nuxt` repository

**Review by manchenkoff — APPROVED** [review]

**Comment by manchenkoff** [comment]
I made a minor change to include `pathe` as a dependency. It was published as `0.5.4` version, please let me know if it works as expected now @ExileofAranei! Thanks again for the contribution 👍

**Comment by ExileofAranei** [comment]
@manchenkoff Everything is resolved correctly now, thanks a lot!

**Pull request merged**
